global:
  scrape_interval: 15s
  scrape_timeout: 5s

scrape_configs:
  - job_name: imap-exporter
    scrape_interval: 300s
    file_sd_configs:
      - files:
        - "/etc/prometheus/file_sd/target_imap_exporter.json"
